run:
  tests: true

linters-settings:
  goimports:
    local-prefixes: github.com/anfilat/go-ews

linters:
  disable:
    - maligned
    - scopelint
  disable-all: false
  presets:
    - bugs
    - format
    - performance
    - unused
  fast: false
